apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadverify.fullname" . }}-db
  labels:
    {{- include "cadverify.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "cadverify.databaseUrl" . | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
