{{- if and .Values.saml.enabled (not .Values.saml.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cadverify.fullname" . }}-saml
  labels:
    {{- include "cadverify.labels" . | nindent 4 }}
type: Opaque
stringData:
  sp-key.pem: {{ (.Values.samlSecrets).spKey | default "" | quote }}
  sp-cert.pem: {{ (.Values.samlSecrets).spCert | default "" | quote }}
{{- end }}
