"""IGES upload ingest (.iges/.igs) — allowlist + magic validation + mesh path.

IGES is routed through the SAME gmsh/OCC mesher as STEP (no new mesher code):
``gmsh.model.occ.importShapes`` reads STEP/IGES/BREP alike, and
``step_to_trimesh_from_bytes`` writes the bytes to a temp file with the ORIGINAL
suffix, so an .iges file meshes through the existing STEP branch once it passes
the allowlist and magic validation.

Always-on, no network. Every gmsh-dependent test skips cleanly when gmsh is
absent (the route degrades to a clean 501 in that case), mirroring
``test_step_mesher``. The IGES input is synthesized by gmsh at test time — no
binary blob is committed.
"""
from __future__ import annotations

import pytest
from fastapi import HTTPException

from src.api.routes import _parse_mesh
from src.api.upload_validation import validate_magic
from src.parsers.step_mesher import is_step_supported, step_to_trimesh_from_bytes


@pytest.fixture(scope="module")
def box_iges_bytes() -> bytes:
    """A real single-solid IGES file (20mm box) generated by gmsh's OCC kernel.

    Mirrors the committed ``box_step_bytes`` conftest fixture exactly, only the
    write suffix differs (.iges). Skips the dependent test cleanly when gmsh is
    not installed. No binary blob is committed — the IGES is synthesized here.
    """
    pytest.importorskip("gmsh", reason="gmsh not installed; IGES path unavailable")
    import os
    import tempfile

    import gmsh

    gmsh.initialize()
    try:
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.model.add("box")
        gmsh.model.occ.addBox(0, 0, 0, 20, 20, 20)
        gmsh.model.occ.synchronize()
        fd, path = tempfile.mkstemp(suffix=".iges")
        os.close(fd)
        gmsh.write(path)
    finally:
        gmsh.finalize()
    try:
        with open(path, "rb") as fh:
            return fh.read()
    finally:
        try:
            os.unlink(path)
        except FileNotFoundError:
            pass


# ── validate_magic: pure structural check (no gmsh needed for rejections) ──────
def test_validate_magic_accepts_real_iges(box_iges_bytes):
    """A real gmsh-written IGES byte-string passes the 80-col section check."""
    validate_magic(box_iges_bytes, ".iges")  # no raise
    validate_magic(box_iges_bytes, ".igs")  # suffix alias, same check


def test_validate_magic_rejects_step_misfiled_as_iges():
    """STEP bytes uploaded as .iges are rejected 400 (never meshed as IGES)."""
    with pytest.raises(HTTPException) as exc:
        validate_magic(b"ISO-10303-21;\nHEADER;\nENDSEC;", ".iges")
    assert exc.value.status_code == 400
    assert "STEP" in exc.value.detail  # static, no user bytes reflected


def test_validate_magic_rejects_random_junk_as_iges():
    """Random binary junk with a .iges suffix is rejected 400."""
    with pytest.raises(HTTPException) as exc:
        validate_magic(b"\x00\x01\x02\xff\xfe garbage not iges \x80\x90" * 8, ".iges")
    assert exc.value.status_code == 400


def test_validate_magic_rejects_stl_as_iges():
    """Binary STL bytes (80-byte header + count) with .iges suffix rejected 400."""
    stl = b"\x00" * 80 + (0).to_bytes(4, "little")  # valid 84-byte binary STL
    with pytest.raises(HTTPException) as exc:
        validate_magic(stl, ".iges")
    assert exc.value.status_code == 400


def test_validate_magic_rejects_ascii_stl_as_iges():
    """ASCII STL ('solid ...') with .iges suffix rejected 400 (short records)."""
    ascii_stl = b"solid part\nfacet normal 0 0 0\nendsolid part\n"
    with pytest.raises(HTTPException) as exc:
        validate_magic(ascii_stl, ".iges")
    assert exc.value.status_code == 400


# ── round-trip: IGES bytes -> existing gmsh mesher -> trimesh.Trimesh ─────────
def test_iges_round_trip_meshes(box_iges_bytes):
    """IGES bytes -> step_to_trimesh_from_bytes -> non-empty trimesh (no new code).

    Same absolute-band caveat as STEP-derived meshes: this is a triangulated
    shell (mesh-level), NOT B-rep — the mesher docstring already states this.
    """
    if not is_step_supported():
        pytest.skip("gmsh not installed; IGES/OCC mesh path unavailable")
    mesh = step_to_trimesh_from_bytes(box_iges_bytes, "part.iges")
    assert len(mesh.faces) > 0
    assert mesh.volume > 0
    # 20mm cube == 8000 mm^3 == 8 cm^3; tessellation is exact for a box.
    assert abs(mesh.volume / 1000.0 - 8.0) < 0.1
    assert all(abs(e - 20.0) < 0.1 for e in mesh.extents)


# ── allowlist: _parse_mesh admits .iges and still 400s unsupported types ──────
def test_parse_mesh_admits_iges(box_iges_bytes):
    """_parse_mesh(.iges) returns (mesh, '.iges') — no unsupported-type 400."""
    if not is_step_supported():
        pytest.skip("gmsh not installed; IGES/OCC mesh path unavailable")
    mesh, suffix = _parse_mesh(box_iges_bytes, "part.iges")
    assert suffix == ".iges"
    assert len(mesh.faces) > 0


def test_parse_mesh_admits_igs_alias(box_iges_bytes):
    """The .igs suffix alias is admitted symmetrically and records suffix '.igs'."""
    if not is_step_supported():
        pytest.skip("gmsh not installed; IGES/OCC mesh path unavailable")
    mesh, suffix = _parse_mesh(box_iges_bytes, "part.igs")
    assert suffix == ".igs"
    assert len(mesh.faces) > 0


def test_parse_mesh_still_rejects_unsupported_suffix():
    """An unsupported suffix (.obj) still raises the unsupported-type 400."""
    with pytest.raises(HTTPException) as exc:
        _parse_mesh(b"o cube\nv 0 0 0\n", "part.obj")
    assert exc.value.status_code == 400
    assert "Unsupported file type" in exc.value.detail
