import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { SiteShell } from "./site-shell";
import { PILOT_WORKFLOWS } from "@/lib/site/navigation";

export type DocumentSection = { id: string; title: string; body: string; bullets?: string[]; href?: string; link?: string; code?: string };
export function DocumentPage({ title, intro, sections, children, label, cta = true }: { title: string; intro: string; sections: DocumentSection[]; children?: React.ReactNode; label: string; cta?: boolean }) {
  const sampleHref = sections.find(section => section.href?.startsWith("/sample"))?.href ?? "/sample";
  const pilotHref = PILOT_WORKFLOWS.includes(label) ? `/company?workflow=${encodeURIComponent(label)}#pilot` : "/company#pilot";
  return <SiteShell><article className="cv-document cv-wrap"><p className="cv-breadcrumb"><Link href="/">CadVerify</Link> / {label}</p><header className="cv-document-hero"><h1>{title}</h1><p>{intro}</p>{cta && <div className="cv-actions"><Link href={sampleHref} className="cv-button">Explore a sample <ArrowUpRight size={18} aria-hidden="true" /></Link><Link href={pilotHref} className="cv-text-link">Talk through your workflow <ArrowRight size={17} aria-hidden="true" /></Link></div>}</header><div className="cv-document-body"><nav className="cv-contents" aria-label="On this page">{sections.map(section => <a key={section.id} href={`#${section.id}`}>{section.title}</a>)}{children && <a href="#pilot">Plan a pilot</a>}</nav><div className="cv-document-sections">{sections.map(section => <section id={section.id} key={section.id}><h2>{section.title}</h2><p>{section.body}</p>{section.bullets && <ul>{section.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul>}{section.code && <pre><code>{section.code}</code></pre>}{section.href && <a href={section.href} className="cv-text-link">{section.link} <ArrowUpRight size={17} aria-hidden="true" /></a>}</section>)}{children}{cta && <div className="cv-document-close"><h2>See the evidence for yourself.</h2><p>Explore a recorded part before bringing your own question.</p><Link href={sampleHref} className="cv-text-link">Open the sample part <ArrowRight size={18} aria-hidden="true" /></Link></div>}</div></div></article></SiteShell>;
}
